port:  5000
markdown: kramdown
name: Pennsylvania Budget Clock
url: http://pabudgetclock.com
title: Pennsylvania Budget Clock
description: "Pennsylvania has languished without a budget for"
encoding: utf-8
timezone: America/Chicago